onboarding = false

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_scope = "all"
[experimental]
pane_history = true
switch_ascii_input_source_in_prefix = true

[theme]
name = "solarized-light"


[keys]
previous_tab = "prefix+ctrl+h"
next_tab = "prefix+ctrl+l"
open_worktree = "prefix+e"
remove_worktree = "prefix+shift+e"
edit_scrollback = ""
focus_agent = "prefix+alt+1..9"
previous_agent = "prefix+alt+k"
next_agent = "prefix+alt+j"
focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"

