[general]
import = [
    "~/.config/alacritty/themes/vscode-light.toml"
]

[env]
term = "xterm-256color"

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
osc52 = "CopyPaste"

[window]
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "BlexMono Nerd Font Mono"
bold_italic.family = "BlexMono Nerd Font Mono"
size = 14.0

[selection]
save_to_clipboard = true
